#!/bin/bash
# Start the 10-round ralph-loop audit (forward evidence v2.1.3 + codebase-wide).
#
# Purpose: 3 deep-audit rounds on the forward-evidence v2.1.3 work (the
# body that just shipped, where codex Round 9+10 caught two real
# blockers AFTER two self-audits had declared production-ready) + 7
# codebase-wide rounds covering data / research / backtest / factors /
# strategy / reporting / scripts. Hard rules force live e2e execution,
# reverse-validation, real-data fixtures, doc-vs-code reconciliation,
# and a zero-changelog README — closing the failure modes that let
# Blockers 1+2 slip past prior audits.
#
# Reference PRD: docs/prd/20260428-ralph_audit_loop_prd.md (auto-
# generated by this script if missing — same pattern as the other
# launchers under dev/scripts/loop/).
#
# Lineage tag:        ralph-audit-2026-04-28 (all 10 rounds share this)
# Max iterations:     10 (3 deep + 7 codebase-wide)
# Completion promise: RALPHAUDIT10DONE
#
# USAGE:
#   bash dev/scripts/loop/start_ralph_audit_loop.sh
#
# WARNING: keep the prompt SINGLE-LINE with ASCII-only characters per
# prior lesson (Chinese punctuation + multi-line prompts break argparse).

set -eo pipefail

PRD_PATH="docs/prd/20260428-ralph_audit_loop_prd.md"

# Sanity: the launcher does NOT auto-write the PRD body — that file
# was committed manually so the PRD lineage is review-traceable. If
# the PRD is missing, fail loudly so the user notices instead of
# silently regenerating.
if [[ ! -f "$PRD_PATH" ]]; then
    echo "ERROR: PRD missing at $PRD_PATH" >&2
    echo "       The PRD must be committed before launching the loop" >&2
    echo "       (commit-traceable lineage)." >&2
    exit 1
fi

# Pre-flight checks (informational only — do not block the launch).
echo "Pre-flight checks (informational)"
echo "================================="

git_clean=1
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "  [WARN] working tree has uncommitted changes — recommended: clean tree before launch"
    git_clean=0
fi
[[ $git_clean -eq 1 ]] && echo "  [OK]   working tree clean"

# Use the project venv python (system python lacks numpy / pandas).
PQS_PYTHON="${PQS_PYTHON:-/home/zibo/miniconda3/envs/pqs/bin/python}"
if [[ ! -x "$PQS_PYTHON" ]]; then
    echo "  [FAIL] PQS python not found at $PQS_PYTHON — set PQS_PYTHON env var" >&2
    exit 1
fi

if [[ -f data/baseline/latest.json ]]; then
    # Schema is { collected, passed, failed, skipped, ... } per
    # dev/scripts/baseline/build_research_baseline_snapshot.py.
    baseline_tests=$(jq -r '.tests.passed // .tests.collected // empty' data/baseline/latest.json 2>/dev/null)
    if [[ -n "$baseline_tests" ]]; then
        echo "  [OK]   baseline test count (passed): $baseline_tests"
    else
        echo "  [WARN] data/baseline/latest.json schema unexpected — Round 3 (A3) will rebuild"
    fi
else
    echo "  [WARN] data/baseline/latest.json missing — Round 3 (A3) will rebuild"
fi

if "$PQS_PYTHON" -c "from core.research.forward import compute_signal_input_hash" >/dev/null 2>&1; then
    echo "  [OK]   forward module imports (via $PQS_PYTHON)"
else
    echo "  [FAIL] forward module imports broken under $PQS_PYTHON — fix before launch" >&2
    exit 1
fi

disk_gb=$(df -BG --output=avail . | tail -1 | tr -dc '0-9')
if [[ ${disk_gb:-0} -lt 10 ]]; then
    echo "  [FAIL] disk free ${disk_gb}G < 10G — halt-condition trip" >&2
    exit 1
fi
echo "  [OK]   disk free ${disk_gb}G"

echo

# Single-line ASCII-only prompt for /ralph-loop:ralph-loop.
# AUTONOMOUS MODE: per PRD §6 "Authorized autonomously".
# Halt per PRD §5; pause-for-user per PRD §6 "Pause for user".
PROMPT='Execute one round per docs/prd/20260428-ralph_audit_loop_prd.md section 4 round briefs. lineage_tag=ralph-audit-2026-04-28 for all audit artifacts. Round 1 = A1 forward evidence module audit. Round 2 = A2 adversarial scenarios. Round 3 = A3 forward documentation sync. Round 4 = B1 data layer. Round 5 = B2 research framework excluding forward. Round 6 = B3 backtest and paper trading parity. Round 7 = B4 factor pipeline and mining. Round 8 = B5 strategy and execution. Round 9 = B6 reporting and diagnostics. Round 10 = B7 scripts and CLI and final consolidation. Hard rules section 3 apply every round: live e2e execution at least 3 commands not just pytest, reverse-validation required for every fix, real-data fixtures only no bdate_range for trading-calendar tests, findings classified blocker non-blocker docs-only cosmetic, doc-vs-code reconciliation per round, README must contain zero update log or changelog content, memo at docs/audit/20260428-ralph_audit_round_NN.md with frontmatter status PASS or FIX_LANDED or BLOCKERS_OPEN, 11-part Chinese summary in docs/20260420-ralph_loop_log.md as R-ralph-audit-2026-04-28-round-NN. AUTONOMOUS MODE: section 6 Authorized autonomously rules; pause to surface per section 6 Pause for user. Halt per section 5 conditions. Push memo to review/claude-collab branch end of every round; push code or doc fixes to main. Emit RALPHAUDIT10DONE only after all 10 rounds complete with status PASS or FIX_LANDED, full unit suite green, README clean of changelog content, baseline refreshed, and CLAUDE.md plus docs/INDEX.md reconciled.'

cat <<EOF
================================================================================
10-Round Ralph-Loop Audit — Setup
================================================================================

PRD:                 $PRD_PATH
Lineage tag:         ralph-audit-2026-04-28
Max iterations:      10 (3 Phase A deep + 7 Phase B codebase-wide)
Completion promise:  RALPHAUDIT10DONE

ROUND STRUCTURE:
  PHASE A — current work deep audit (forward evidence v2.1.3)
    R1 / A1 — forward evidence module audit
              core/research/forward/{bar_hash,revalidate,runner,
              source_layer,manifest_schema}.py contract re-derivation;
              4 live e2e runs incl reverse-validation of v2.1.3 fixes
    R2 / A2 — adversarial scenarios + regression hardening
              >=10 scenarios codex did NOT cover; gap tests with real-
              data fixtures
    R3 / A3 — forward documentation sync
              CLAUDE.md / README.md / docs/INDEX.md aligned to v2.1.3;
              REMOVE README changelog if any; baseline rebuild

  PHASE B — codebase-wide audit
    R4  / B1 — data layer (BarStore / aggregator / validator / splits / yfinance / fetch scripts)
    R5  / B2 — research framework (robustness / concentration / OOS; forward already covered)
    R6  / B3 — backtest + paper trading parity (M11a/b drift, M14 NaN)
    R7  / B4 — factor pipeline + mining (PRODUCTION/RESEARCH separation, factor_guard)
    R8  / B5 — strategy + execution layer (multi_factor / kill_switch / multi-TF timing)
    R9  / B6 — reporting + diagnostics (master_report / detectors / drift_metrics)
    R10 / B7 — scripts / CLI + final consolidation
              (--help on every script + run_all.sh paths + master
              issue list across B1-B6)

HARD RULES (every round):
  1. Live-code execution required (>=3 e2e cmds; stdout quoted verbatim)
  2. Reverse-validation required for every fix (revert -> reproduce ->
     re-apply -> close)
  3. Real-data fixtures only (no bdate_range for trading-calendar tests)
  4. Findings classified: blocker / non-blocker / docs-only / cosmetic
  5. Doc-vs-code reconciliation per round
  6. README contains NO update log / changelog (remove if found)
  7. Memo template per PRD section 7
  8. 11-part Chinese summary in docs/20260420-ralph_loop_log.md
  9. Push memo to review/claude-collab; code fixes to main

AUTHORITY:
  Autonomous: bug fixes / docstrings / regression tests / docs edits / baseline rebuild
  Pause:      schema changes / config edits / public-API deletions /
              dependency adds / invariant-constraint changes / live
              forward-observe runs

HALT CONDITIONS:
  1. 10 rounds completed (ceiling -> RALPHAUDIT10DONE)
  2. Test count drops by > 10 vs round-0 baseline
  3. Core import breaks
  4. Finding requires schema migration / new PRD
  5. Reverse-validation fails (claimed fix doesn't close the bug)
  6. CLAUDE.md / README drift needs cross-round code changes
  7. Disk < 10 GB

PRE-FLIGHT (already run above): see status lines.

--------------------------------------------------------------------------------
PASTE THIS INTO CLAUDE CODE (single line, starts with /ralph-loop:ralph-loop):
--------------------------------------------------------------------------------

/ralph-loop:ralph-loop "$PROMPT" --max-iterations 10 --completion-promise RALPHAUDIT10DONE

--------------------------------------------------------------------------------
During the loop (informational):
--------------------------------------------------------------------------------

- Per-round artifacts:
  * Full memo:     docs/audit/20260428-ralph_audit_round_NN.md
  * 11-part CN:    docs/20260420-ralph_loop_log.md (R-ralph-audit-2026-04-28-round-NN)
  * Code commits:  main
  * Memo commits:  review/claude-collab

- To pause mid-loop:
       rm .claude/ralph-loop.local.md
  Or use /ralph-loop:cancel-ralph

- To inspect status mid-loop:
       ls docs/audit/20260428-ralph_audit_round_*.md
       grep '^status:' docs/audit/20260428-ralph_audit_round_*.md

- Final round (R10) must:
  * Emit <promise>RALPHAUDIT10DONE</promise>
  * Master issue list cross-referenced from R10 memo to all
    prior memos by issue ID (R<NN>.<idx>)
  * README clean of changelog content
  * data/baseline/latest.json regenerated if test count drift
  * docs/INDEX.md updated with new memos + this PRD entry
  * CLAUDE.md TODO checklist + Confirmed Done synced to round
    findings

EOF
